data_dir: 'data'
target_dir: 'data/gen'
t5_model_path: 'google/flan-t5-base'
bert_model_path: 'bert-base-uncased'
spacy_model_path: 'en_core_web_lg'
chat_gpt_model_path: 'gpt-4o' #gpt-4, gpt-3.5-turbo
model_size: 'base'
label_list:  ['positive', 'negative', 'neutral']
emb_dim: 300
openai_token: OPENAI_API_KEY
output_channels: 100
speaker_emb_dims: 300
project_dims: 300
max_length: 300
batch_size: 64
gen_batch_size: 10
epoch_size: 20
train_mode: random
filters: [3,4,5]
dropout: 0.5
shuffle: True
learning_rate: 1e-4
bert_lr: 2e-4
patience: 100
max_grad_norm: 1.0
warmup_proportion: 0.1
gradient_accumulation_steps: 1
adam_epsilon: 1e-8
warmup_steps: 0
weight_decay: 0.01
seed: 42